// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzQkmViRP7OE5z_iUnkc_nzYxlXJLMuXg',
    appId: '1:204492590108:web:c4622347433b4663f8a3d9',
    messagingSenderId: '204492590108',
    projectId: 'qalyoubfantasy',
    authDomain: 'qalyoubfantasy.firebaseapp.com',
    storageBucket: 'qalyoubfantasy.firebasestorage.app',
    measurementId: 'G-JLTLJT59ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBydi2LLZxmcxAHXckml7xgReyrrSUOwi4',
    appId: '1:204492590108:android:3b0d7cbec20ba4ebf8a3d9',
    messagingSenderId: '204492590108',
    projectId: 'qalyoubfantasy',
    storageBucket: 'qalyoubfantasy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3hQRJ_TDWaNnNs0kSzqrdTiREUFbkMi8',
    appId: '1:204492590108:ios:3186edf6ec294fe7f8a3d9',
    messagingSenderId: '204492590108',
    projectId: 'qalyoubfantasy',
    storageBucket: 'qalyoubfantasy.firebasestorage.app',
    iosBundleId: 'com.example.qalyoubFantasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3hQRJ_TDWaNnNs0kSzqrdTiREUFbkMi8',
    appId: '1:204492590108:ios:3186edf6ec294fe7f8a3d9',
    messagingSenderId: '204492590108',
    projectId: 'qalyoubfantasy',
    storageBucket: 'qalyoubfantasy.firebasestorage.app',
    iosBundleId: 'com.example.qalyoubFantasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzQkmViRP7OE5z_iUnkc_nzYxlXJLMuXg',
    appId: '1:204492590108:web:edaa5a250a271b84f8a3d9',
    messagingSenderId: '204492590108',
    projectId: 'qalyoubfantasy',
    authDomain: 'qalyoubfantasy.firebaseapp.com',
    storageBucket: 'qalyoubfantasy.firebasestorage.app',
    measurementId: 'G-X5BRYLTF6D',
  );
}
